version: '3.8'

services:
  postgres-test:
    image: postgres:15
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: video_test_db
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5435:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d video_test_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - test-network

volumes:
  postgres_test_data:

networks:
  test-network:
    driver: bridge