apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-postgres
  namespace: video-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-postgres
      component: video-processor
      project: video-processor
  template:
    metadata:
      labels:
        app: video-postgres
        component: video-processor
        project: video-processor
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "video_db"
        - name: POSTGRES_USER
          value: "video_user"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: video-processor-secret
              key: POSTGRES_PASSWORD
        # Remove volume mount for no-storage version
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - video_user
            - -d
            - video_db
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - video_user
            - -d
            - video_db
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 3