apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: video-postgres-pvc
  namespace: video-processor
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: hostpath