apiVersion: v1
kind: Service
metadata:
  name: video-rabbitmq
  namespace: video-processor
  labels:
    app: video-rabbitmq
spec:
  type: ClusterIP
  ports:
  - port: 5672
    targetPort: 5672
    protocol: TCP
    name: amqp
  - port: 15672
    targetPort: 15672
    protocol: TCP
    name: management
  selector:
    app: video-rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: video-rabbitmq-management
  namespace: video-processor
  labels:
    app: video-rabbitmq
spec:
  type: LoadBalancer
  ports:
  - port: 15672
    targetPort: 15672
    protocol: TCP
    name: management
  selector:
    app: video-rabbitmq