apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-rabbitmq
  namespace: video-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-rabbitmq
      component: video-processor
      project: video-processor
  template:
    metadata:
      labels:
        app: video-rabbitmq
        component: video-processor
        project: video-processor
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management-alpine
        ports:
        - containerPort: 5672
          name: amqp
        - containerPort: 15672
          name: management
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: "video_user"
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: video-processor-secret
              key: RABBITMQ_DEFAULT_PASS
        # Remove volume mount for no-storage version
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - rabbitmq-diagnostics
            - ping
          initialDelaySeconds: 30
          periodSeconds: 30
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - rabbitmq-diagnostics
            - ping
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 3