apiVersion: v1
kind: Secret
metadata:
  name: video-processor-secret
  namespace: video-processor
type: Opaque
data:
  # POSTGRES_PASSWORD (base64 encoded): video_password
  POSTGRES_PASSWORD: dmlkZW9fcGFzc3dvcmQ=
  # RABBITMQ_DEFAULT_PASS (base64 encoded): guest
  RABBITMQ_DEFAULT_PASS: Z3Vlc3Q=