apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: video-uploads-pvc
  namespace: video-processor
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: hostpath